-- Migration 003 has been superseded by runtime schema checks in the API layer.
-- When the API boots it ensures the orders table contains the payment columns
-- and rebuilds order_items to support part references if necessary. This file
-- remains as a placeholder so previously documented migration instructions do
-- not error when executed again.
